name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Make package
        run: ./gradlew package

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: distributable-${{ matrix.os }}
          if-no-files-found: ignore
          path: |
            build/app/build/**/*.dmg
            build/app/build/**/*.msi
            build/app/build/**/*.deb

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            build/app/build/**/*.dmg
            build/app/build/**/*.msi
            build/app/build/**/*.deb

